FROM alpine:3

ENV PIPENV_VENV_IN_PROJECT=1
EXPOSE 5000

WORKDIR /app
COPY . /app

RUN apk update && \
    apk add \
      shadow \
      pipx && \
    PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install pipenv && \
    pipenv sync && \
    useradd user && \
    chown -R user:user /app

USER user

CMD pipenv run flask run --host=0.0.0.0
